### ISSUE TITLE
Any chance for updating this?

### ISSUE THREAD

**Issue by luckyankit** [rjshanahan/facebook_m_scraper#1]
Hello,

I've tried this version and doesn't work anymore.. any chance that you may look into it and make it work again?

TIA

**Comment by rjshanahan** [comment]
Howdy... I'll take a look. Quick glance the structure/HTML of the fb.m page has changed (obviously haven't touched this for ages!) The selenium steps and HTML parser needs to amended.

**Comment by rjshanahan** [comment]
Did [this](https://github.com/rjshanahan/facebook_m_scraper/commit/2a9ddd59adbc22e8761a3cb63ad1e8f1ba52cf06#commitcomment-21688750) explain things? I added a [Jupyter Notebook](https://github.com/rjshanahan/facebook_m_scraper/blob/master/notebook_facebook_m_scraper.ipynb) to walk through the steps.
